### ISSUE TITLE
Outdated elasticsearch package.

### ISSUE THREAD

**Issue by galkin** [gojob-1337/node-ts-elasticsearch#4]
Greetings!

During this package installation: 
```
npm install @gojob/ts-elasticsearch

+ @gojob/ts-elasticsearch@1.3.2
updated 1 package and audited 78393 packages in 7.705s
found 3 vulnerabilities (1 low, 1 moderate, 1 high)
  run `npm audit fix` to fix them, or `npm audit` for details
```
The vulnerabilities path is `@gojob/ts-elasticsearch > elasticsearch > lodash`

Could you update elasticsearch package to new version and publish?

**Comment by Kamar-Meddah** [comment]
@galkin 
all you have to do is to run 'npm audit fix'

**Comment by malisetti** [comment]
use @elastic/elasticsearch package
